### ISSUE TITLE
<PortableText> is not a valid SSR component.

### ISSUE THREAD

**Issue by vhendin** [portabletext/svelte-portabletext#13]
Trying to set up a Svelte app with Typescript. When I'm trying to use the PortableText component it states that it's not a valid SSR component. I fetch some data from Sanity on +page.server.ts then pass it to my component `PortableText.svelte`. This is what it looks like:

```javascript
<script lang="ts">
	/** @type {import('./$types').PageData} */
	import PortableText from '@portabletext/svelte';
	import type { PortableTextType } from './types';

	export let blocks: PortableTextType;
</script>

<div>
	{#if blocks}
		<PortableText value={blocks} />
	{/if}
</div>

```

In this component I get an error saying `JSX element type 'PortableText' does not have any construct or call signatures.ts(2604)`.

When rendering I get the following:

```
<PortableText> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules
```

It based on the latest version of sveltekit created with `npm create svelte@latest`, v3.47.0.

Any ideas?

Edit: I've been following the docs around server pages on the [official docs](https://kit.svelte.dev/docs/routing#page-page-server-js) and everything has worked smoothly until rendering PortableText.

**Comment by tessellator** [comment]
I think you need to change your import to look like:
```
import { PortableText } from '@portabletext/svelte';
```

I was having the same issue. My import statement looked the same as your (following the [plugin docs](https://www.sanity.io/plugins/portabletext-svelte) on Sanity's website). After making that change and changing `blocks` prop name to `value` (which you have already done), the `PortableText` component started working correctly for me.

**Comment by vhendin** [comment]
Oh my, embarrassing mistake. It works. Thanks a lot @tessellator!

**Comment by tessellator** [comment]
Not embarrassing at all. We're all in this together. :)

**Comment by vhendin** [comment]
Also, the [official Sanity.io page](https://www.sanity.io/plugins/portabletext-svelte) for the plugin doesn't have the brackets at all. Maybe that's where I saw it.

**Comment by matt416** [comment]
I just made the same mistake. I followed the official Sanity docs too, that must be the culprit 😄 

Thank you for this issue resolution
