### ISSUE TITLE
Getting a TypeError in SvelteKit

### ISSUE THREAD

**Issue by maks112v** [portabletext/svelte-portabletext#16]
I just installed PortableText and having issues rendering a single block of text. It works when navigating to a screen but throws the error when going directly to a screen. I keep getting a type issue:
```
TypeError: Cannot read properties of undefined (reading 'nestLists')
```
<img width="359" alt="CleanShot 2023-01-27 at 20 42 25@2x" src="https://user-images.githubusercontent.com/11082252/215235115-d8e4cf04-0a3a-44c9-b398-5e230aaca303.png">

```
content: [
    {
      _key: '72d600bf04cc',
      _type: 'block',
      children: [Array],
      markDefs: [],
      style: 'normal'
    }
  ],
```

**Comment by Kansuler** [comment]
I have the same problem. It's the peer dependency @portabletext/toolkit that has been upgraded from 1.0.5 to 1.0.8, and introduced a breaking change.

If you're using `yarn` to install dependencies, you can add this to your package.json to look the dependency to version 1.0.5. (unsure if npm has support for this, but you can try).

```js
{
	"name": "web",
	"version": "0.0.1",
	"scripts": {
		...
	},
	"devDependencies": {
		...
	},
	"resolutions": {
		"@portabletext/svelte/@portabletext/toolkit": "1.0.5"
	},
	"type": "module"
}
```

**Comment by maks112v** [comment]
Awesome thank you for the solution! Should we leave it open as a bug or close this issue?

**Comment by rexxars** [comment]
Thanks for reporting - could you try out the prerelease of the new 2.0 branch and let us know if that solves your issue without the resolutions fix?

In your `package.json`:
```js
{
  // ...
  "dependencies": {
    // ...
    "@portabletext/svelte": "2.0.0-0"
  }
}
```

Then install dependencies with `yarn`/`npm install`.

**Comment by dev-ofty** [comment]
@rexxars thank you for the pre-release, I can confirm that it worked for me.

**Comment by multiplehats** [comment]
Can confirm that this fixes a bunch of issues for me too :)!

**Comment by rexxars** [comment]
2.0.0 is released, which should fix this one! Thanks for testing!
