### ISSUE TITLE
Fails in SSR

### ISSUE THREAD

**Issue by yfi** [portabletext/svelte-portabletext#18]
I am trying to prerender a static website with data fetched from sanity, with `ssr = true`

```svelte
<PortableText value={blocks}/>
```

Gives me this error during the build process:

```js
import { spanToPlainText, isPortableTextToolkitList, isPortableTextListItemBlock, buildMarksTree, isPortableTextToolkitSpan, isPortableTextBlock, isPortableTextToolkitTextNode, nestLists, LIST_NEST_MODE_HTML } from "@portabletext/toolkit";
                                                                                                                                                                                            ^^^^^^^^^^^^^^^^^^^
SyntaxError: Named export 'LIST_NEST_MODE_HTML' not found. The requested module '@portabletext/toolkit' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@portabletext/toolkit';
const { spanToPlainText, isPortableTextToolkitList, isPortableTextListItemBlock, buildMarksTree, isPortableTextToolkitSpan, isPortableTextBlock, isPortableTextToolkitTextNode, nestLists, LIST_NEST_MODE_HTML } = pkg;
```

When I do this:
```svelte
{#if browser}
  <PortableText value={blocks} />
{/if}
```

The build process completes, but the rich text content is hydrated in the browser. I would like SSR the content to the page

**Comment by s-rd** [comment]
Also having this issue – haven't found a fix yet.

**Comment by s-rd** [comment]
Getting a similar error with `nestLists` being undefined when SSR'ing. 

```bash
Cannot read properties of undefined (reading 'nestLists')
TypeError: Cannot read properties of undefined (reading 'nestLists')
    at PortableText.svelte:27:12
```

If I throw it inside a `browser` environment like @yfi does, it seems to work, but I'd also like to SRR the content.

(Perhaps related to https://github.com/portabletext/toolkit/issues/7?)

**Comment by s-rd** [comment]
Yeah, I get a similar error to what you posted originally, too, in some cases. Not sure what seems to trigger one or the other.

**Comment by rexxars** [comment]
Could you try the new `@portabletext/svelte@2.0.0` and see if that helps things?

**Comment by s-rd** [comment]
@rexxars That fixes it! Incredible. _Thank_ you. 🙏🏻

**Comment by rexxars** [comment]
Great to hear! Closing this, please feel free to comment/open a new issue if you're still seeing issues with this

**Comment by fschroiff** [comment]
@rexxars I am using `@portabletext/svelte@2.0.0` and have the exact same error as OP: `SyntaxError: Named export 'LIST_NEST_MODE_HTML' not found.` This is in a new project that I am building locally.
