### ISSUE TITLE
Support <a> and <br> tags

### ISSUE THREAD

**Issue by james-camilleri** [portabletext/svelte-portabletext#2]
Are there any plans for default support of `<a>` and `<br>` tags? Would you like me to submit a pull request perhaps, or is it purposefully going to be left for users to add custom serializers?

**Comment by hdoro** [comment]
Hey @james-camilleri, thanks for reporting!

This library currently doesn't handle `<br>` tags and that's not intentional. I'm currently working on supporting it, thank you for flagging 🙏 

As for "default support" of `<a>` tags, I'm not sure I follow. Do you mean rendering marks with `_type: "link"` as plain anchors by default? If so, also something I'm working on :)

**Comment by james-camilleri** [comment]
Hey @hdoro sorry for the late reply, I've been really swamped 😪
Yes, that's what I mean by the `<a>` tag support - I think. I've worked around it with a custom serializer as suggested, but it would be nice to get them working out of the box. I've also worked around the line break thing by forcing newlines via CSS, something I didn't think of originally, which might actually be the "correct" approach. Although I think having an option to inject `<br>` tags for newlines might be useful though.

I'm pretty busy for the next few weeks but if you'd like help with getting some of that functionality give me a shout. 😊

**Comment by murl-digital** [comment]
Hello, is there any updates on these? Having a default anchor would be really nice to have. If you need help getting the feature out, let me know, I'd be happy to help!

**Comment by dennisregalado** [comment]
Also looking to see if there is an update for supporting line breaks as well, would love to contribute in anyway!

**Comment by hdoro** [comment]
@dennisregalado @murl-digital @james-camilleri you can try out the upcoming v1 version that fixes these issues by installing `@portabletext/svelte@1.0.0-next.1` and [following the migration guide here](https://github.com/portabletext/svelte-portabletext/blob/feat/v1/MIGRATING-v1.md).

We changed several aspects of the API to more closely align with `@portabletext/react`, let us know what you think :)

**Comment by hdoro** [comment]
1.0.0 is live to fix these issues :)
