### ISSUE TITLE
@portabletext_toolkit.js does not provide an export named 'ToolkitNestedPortableTextSpan'

### ISSUE THREAD

**Issue by kenjonespizza** [portabletext/svelte-portabletext#7]
Hi @hdoro 👋 !

I ran in to an error here that I've tried fixing, but I don't have the typescript skills to figure out.

I was able to replicate from cloning this repo, installing packages, and running `dev`.  Image of error attached.

<img width="947" alt="image" src="https://user-images.githubusercontent.com/1581912/168890010-78c93708-5b1e-4773-ae51-140e670d6e1d.png">

Thanks for your amazing work on this package 👍

**Comment by dennisregalado** [comment]
Experiencing the same issue — seem's to only affect dev mode.

**Comment by hdoro** [comment]
Hey Ken & Dennis! Thank you for reporting, I've cloned a fresh copy of this repo and can attest the error above is showing. Working on it!

That said, I can't reproduce the issue in websites consuming the package, including sites using Typescript. What am I missing? Is this breaking your usage outside the library site?

**Comment by hdoro** [comment]
1.0.1 fixes this issue. The root cause was a TS type import in a Svelte file, which is now according to Svelte's expectation (see [this commit](https://github.com/portabletext/svelte-portabletext/commit/852bfb2bae514c84ed8acd495489b29ea9fd5f60)).

Thanks for reporting 😄
