### ISSUE TITLE
Guide on Sanity-io is outdated

### ISSUE THREAD

**Issue by kamerat** [portabletext/svelte-portabletext#8]
https://www.sanity.io/plugins/portabletext-svelte

I followed the "readme" on the blog post instead of here.
This resulted in me loosing more of my already lacking hair trying to use the (probably outdated) "blocks" prop.

**Comment by NormalAndrew** [comment]
@kamerat What blog post are you referring to?  Can you link to it?

**Comment by kamerat** [comment]
@NormalAndrew, I'm referig to the link above. (https://www.sanity.io/plugins/portabletext-svelte) I refered to it as a "blog post". I am not sure where the data in that article/blog post/page comes from.  

In the article linked above, _Henrique Doro_ states us to use "blocks" prop for the blocks, but in reality, it should be the value prop as stated in the [readme](https://github.com/portabletext/svelte-portabletext/blob/main/README.md#customizing-rendering) here.

**Comment by kmelve** [comment]
This seems to be up to date now. Closing.
