### ISSUE TITLE
Anyone experiencing issue with list being individually wrap in <ul>?

### ISSUE THREAD

**Issue by psntr** [portabletext/svelte-portabletext#85]
I'm having an issue where each lines of my list item are individually wrapped in a `<ul>` tag. 

Not sure if there is a way around that? In case it helps to debug, I'm attaching what I have in Sanity:
<img width="596" alt="ScreenShot 2024-03-01 at 19 31 21" src="https://github.com/portabletext/svelte-portabletext/assets/20617539/6f07c422-f7da-4d21-843a-d6dbb652a3b5">
<img width="862" alt="ScreenShot 2024-03-01 at 19 32 17" src="https://github.com/portabletext/svelte-portabletext/assets/20617539/079503be-547c-4331-8f91-0501392f7cb6">

**Comment by abteilung** [comment]
I actually was facing the same issue too. I was building a PageBuilder module in which I was iterating through all blocks to render them individually according to their type. Problem was that each listItem was returned as an individual block.

I got around it by just using the types property in PortableText.

**Comment by psntr** [comment]
Thanks for the insights, could you expand a bit more regarding the property in PortableText?

**Comment by abteilung** [comment]
Here is how I configure my PortableText component. 

`
<script>
	import { PortableText } from '@portabletext/svelte';

	import ListsWrapper from '$lib/components/Lists.svelte';
	import ListItemWrapper from '$lib/components/ListItems.svelte';

	import Code from '$lib/components/Code.svelte'
	import Video from '$lib/components/Video.svelte'
	import ProductReference from '$lib/components/ProductReference.svelte'
</script>

<PortableText
	value={content}
	components={{
		types: {
			code: Code,
			video: Video,
			productReference: ProductReference,
		},
		list: {
			bullet: ListsWrapper,
			number: ListsWrapper
		},
		listItem: {
			normal: ListItemWrapper
		}
	}}
/>
`

Does this help?

**Comment by psntr** [comment]
Thank you, it's working with declaring the components that way, closing the issue.
